require "digest/md5"
require_relative "features/support/libs/mongo"

def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end

task :test do
  puts "Executando uma tarefa de teste"
end

task :local_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))

  users = [
    { name: "Everton Souza", email: "everton@gmail.com", password: to_md5("pwd123") },
    { name: "RaFael Souza", email: "rafael@gmail.com", password: to_md5("pwd123") },
    { name: "Eloy Casagrande", email: "eloy@gmail.com", password: to_md5("pwd123") },
  ]

  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

  sh "cucumber"
end

task :hmg_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))

  users = [
    { name: "Everton Souza", email: "everton@gmail.com", password: to_md5("pwd123") },
    { name: "RaFael Souza", email: "rafael@gmail.com", password: to_md5("pwd123") },
  ]

  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

  sh "cucumber"
end
